apiVersion: v1
kind: Service
metadata:
  name: taskmaster-pro-service
  labels:
    app: taskmaster-pro
spec:
  selector:
    app: taskmaster-pro
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: LoadBalancer